### ISSUE TITLE
Investigate cargo bay occlusion

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/MkIVSystem#36]
Some kind of issue is preventing a set of bays that include either a Mk4 Tail Cargo Bay or a Mk4 Crew Cabin from closing properly. 

Summarized in these two posts:

http://forum.kerbalspaceprogram.com/index.php?/topic/91713-122-mark-iv-spaceplane-system-minor-bugfix-update-march-10-2017/&do=findComment&comment=2996690

http://forum.kerbalspaceprogram.com/index.php?/topic/91713-122-mark-iv-spaceplane-system-minor-bugfix-update-march-10-2017/&do=findComment&comment=2997805

**Comment by JimmyCushnie** [comment]
Hi, I'm having an issue where kerbals can't exit the bottom hatch of the MK4 Crew Cabin. If I click "EVA" I get the message "Hatch is obstructed, can't exit". Is this the same issue?
![screenshot5](https://user-images.githubusercontent.com/32693298/107108382-74490600-6805-11eb-99eb-6f644e31462d.png)

**Comment by HurryStarfish** [comment]
I'm not a modder and don't really know how the KSP part configs work, but after experimenting a bit with the the aerodynamic debug outputs, I found that the Tail Cargo Tail appears to shield its contents when it is fully open, instead of when it is closed. Going into `mk4cargotail-1.cfg` and changing
```
	MODULE
	{
		name = ModuleCargoBay
		DeployModuleIndex = 0
		closedPosition = 0
		lookupRadius = 4
		nodeOuterForeID = bottom1
	}
```
into
```
	MODULE
	{
		name = ModuleCargoBay
		DeployModuleIndex = 0
		closedPosition = 1
		lookupRadius = 4
		nodeOuterForeID = bottom1
	}
```
fixes this for me.
No idea how to fix the Mk4 Crew Cabin though. It seems to be considered permanently open to the air, which makes any part placed inside it or in adjacent cargo bays experience drag. In a plane built like `Mk4 Cockpit → Mk4 Crew Cabin → Mk4 Cargo Bay → ...`, nothing inside the cargo bay is ever shielded, whereas with
`Mk4 Cockpit → Mk4 Crew Cabin → Mk4 Drone Core → Mk4 Cargo Bay → ...` or `Mk4 Cockpit → Mk4 Crew Cabin → Mk4 Fuselage → Mk4 Cargo Bay → ...`, only the contents of the crew cabin itself are unshielded while the regular cargo bays work. Maybe it's a similar issue with `closedPosition`, considering the crew cabin doesn't actually have any open/close actions?

**Comment by ChrisAdderley** [comment]
I've made significant improvements to this in the latest release
